### ISSUE TITLE
java.lang.NoSuchFieldException: handle

### ISSUE THREAD

**Issue by jose-mazella** [APISENSE/embed-influxDB#20]
I am trying to set up a test context on Spring Boot with JDK 11 and am having the following problem:

`20:16:22.120 [main] INFO io.apisense.embed.influx.InfluxServer - Initializing server: io.apisense.embed.influx.InfluxServer@57c758ac
20:16:22.206 [main] INFO io.apisense.embed.influx.InfluxServer - Starting server: io.apisense.embed.influx.InfluxServer@57c758ac
20:16:22.208 [main] DEBUG io.apisense.embed.influx.configuration.InfluxConfigurationWriter - Writing configuration file into: /var/folders/ny/jtc4x5md3gb7ff_79k7srk_80000gn/T/influxdb.config7344154943554392480111696521971499
20:16:22.222 [main] DEBUG io.apisense.embed.influx.execution.embed.InfluxProcess - Using config file /var/folders/ny/jtc4x5md3gb7ff_79k7srk_80000gn/T/influxdb.config7344154943554392480111696521971499
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:109)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$2.getPid(Processes.java:209)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:98)
	at io.apisense.embed.influx.execution.embed.InfluxProcess.<init>(InfluxProcess.java:25)
	at io.apisense.embed.influx.execution.embed.InfluxExecutable.start(InfluxExecutable.java:24)
	at io.apisense.embed.influx.execution.embed.InfluxExecutable.start(InfluxExecutable.java:11)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
	at io.apisense.embed.influx.execution.InfluxExecutor.start(InfluxExecutor.java:41)
	at io.apisense.embed.influx.InfluxServer.start(InfluxServer.java:65)
	at br.com.picpay.conciliations.TEste.main(TEste.java:41)`

Taking a good look at the problem, I noticed that the `java.lang.ProcessImpl` class does not have the `handle` field, but the `processHandle` field, so the exception is thrown.

Regards.

**Comment by aveuiller** [comment]
Hello, 

It seems to be an issue due to the version of `de.flapdoodle.embed.process` we use. If you can build the dependency using at least the version 2.0.3, it should work.

See https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/241 for more info.

I will try to make a new package asap. :)

**Comment by aveuiller** [comment]
I released v1.2.1 that should solve your issue.

Don't hesitate to open this issue again if you still have a problem. :)
